name: API-projects CI/CD

on:
  push:
    branches: ['main', 'dev']
  pull_request:
    branches: ['main', 'dev']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm install

  check-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Check for outdated dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Check for outdated dependencies
        run: npm outdated

  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
           node-version: '16.x'
           cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Update dependencies
        run: npm update
